<form role="form" class="col-md-12" method="post">
    <div class="form-group">
        <label for="field-name">Nome</label>
        <input type="text" class="form-control" id="field-name" name="name" value="<?php echo $entity->getName() ?>">
    </div>

    <div class="form-group">
        <label for="field-state">Estado</label>
        <input type="text" class="form-control" id="field-state" name="state" value="<?php echo $entity->getState() ?>">
    </div>
    
    <div class="form-group">
        <label for="field-city">Cidade</label>
        <input type="text" class="form-control" id="field-city" name="city" value="<?php echo $entity->getCity() ?>">
    </div>
    
    <div class="form-group">
        <label for="field-district">Bairro</label>
        <input type="text" class="form-control" id="field-district" name="district" value="<?php echo $entity->getDistrict() ?>">
    </div>
    
    <div class="form-group">
        <label for="field-address">Endereço</label>
        <input type="text" class="form-control" id="field-address" name="address" value="<?php echo $entity->getAddress() ?>">
    </div>
    
    <div class="form-group">
        <label for="field-email">E-mail</label>
        <input type="text" class="form-control" id="field-email" name="email" value="<?php echo $entity->getEmail() ?>">
    </div>
    
    <div class="form-group">
        <label for="field-phone">Telefone</label>
        <input type="text" class="form-control" id="field-phone" name="phone" value="<?php echo $entity->getPhone() ?>">
    </div>
    
    <div class="form-group">
        <label for="field-cpf">CPF</label>
        <input type="text" class="form-control" id="field-cpf" name="cpf" value="<?php echo $entity->getCpf() ?>">
    </div>
    
    <div class="form-group">
        <label for="field-rg">RG</label>
        <input type="text" class="form-control" id="field-rg" name="rg" value="<?php echo $entity->getRg() ?>">
    </div>
    
    <div class="form-group">
        <label for="field-birth-date">Data de nascimento</label>
        <input type="text" class="form-control" id="field-birth-date" name="birthDate" value="<?php echo is_object($entity->getBirthDate()) ? $entity->getBirthDate()->format('Y-m-d') : null ?>">
    </div>

    <button type="submit" class="btn btn-default">Salvar</button>
</form>