
<div class="row">

    <div class="col-md-12">
        <?php
        echo $this->flashMessenger()
            ->setMessageOpenFormat('<div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
            </button>
            <p>')
            ->setMessageSeparatorString('</p><p>')
            ->setMessageCloseString('</p></div>')
            ->render('info', array('alert', 'alert-info', 'alert-dismissible'));
        ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Contatos</h3>
            </div>

            <div class="panel-body">
                <?php if ($records) : ?>
                <table class="table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nome</th>
                            <th>E-mail</th>
                            <th>Telefone</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <?php foreach ($records as $record) : ?>
                    <tbody>
                        <tr>
                            <td><?php echo $record->getId() ?></td>
                            <td><?php echo $record->getName() ?></td>
                            <td><?php echo $record->getEmail() ?></td>
                            <td><?php echo $record->getPhone() ?></td>
                            <td>
                                <a href="<?php echo $this->url(
                                    'contact', array(
                                        'action' => 'edit',
                                        'id' => $record->getId(),
                                    )
                                ) ?>">Editar</a>
                                <a href="<?php echo $this->url(
                                    'contact', array(
                                        'action' => 'delete',
                                        'id' => $record->getId(),
                                    )
                                ) ?>">Apagar</a>
                            </td>
                        </tr>
                    </tbody>
                    <?php endforeach ?>
                </table>
                <?php else : ?>
                <p>Nenhum registro encontrado.</p>
                <?php endif ?>
            </div>
        </div>
        <a class="btn btn-primary" href="<?php echo $this->url('contact', array('action' => 'add')) ?>">Cadastrar novo</a>
    </div>

</div>
